name: Certbot website CI
on:
  push:
  pull_request:
  schedule:
    # Run at 4pm UTC or 9am PST
    - cron: "0 16 * * *"
env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  NODE_ENV: production
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 8.12.0
      - name: Install Node packages
        run: |
          set -x
          gulp --version || true
          npm install gulp
          gulp --version || true
          npm install -g gulp
          gulp --version || true
          npm install gulp-cli
          gulp --version || true
          npm install -g gulp-cli
          gulp --version || true
